name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    if-you-build-it:
      env:
        PYTHON_VERSION: "3.6.13"

      runs-on: ubuntu-latest

      steps:
        -
          uses: actions/checkout@v2
        -
          name: setup buildx
          uses: docker/setup-buildx-action@v1
        -
          name: login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        -
          name: Build the Docker image
          uses: docker/build-push-action@v2

          with:
            push: true
            tags: gladiatr72/python:${{ env.PYTHON_VERSION }}
            build-args:
              - PYTHON_VERSION=${{ env.PYTHON_VERSION}}
              - BUILD_ARGS=--enable optimizations --with-lto
