name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.6.13

    steps:
    -
      uses: actions/checkout@v2
    -
      name: setup buildx
      uses: docker/setup-buildx-action@v1
    -
      name: login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: gladiatr72/python: ${{ env.PYTHON_VERSION }}
